name: Publish

on:
  release:
    types: [published]
  push:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Build Release
        run: | 
           dotnet publish -c Release --self-contained true -p:DebugType=embedded -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -r win-x64
           dotnet publish -c Release --self-contained true -p:DebugType=embedded -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -r linux-x64
           mkdir artifacts
           mv ./Bambixploit/bin/Release/net5.0/win-x64/publish/Bambixploit.exe ./artifacts/bambixploit.exe
           mv ./Bambixploit/bin/Release/net5.0/linux-x64/publish/Bambixploit ./artifacts/bambixploit
      - name: Tree
        run: |
          tree ./artifacts
#      - name: Publish
#        uses: softprops/action-gh-release@v1
#        with:
#          files: "App*"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
